# Generated by Django 4.2.4 on 2023-08-09 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('descripion', models.CharField(max_length=500)),
                ('quantity', models.FloatField()),
                ('cost', models.FloatField()),
                ('isAllergen', models.BooleanField(default=False)),
                ('minTheshold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tableNumber', models.IntegerField()),
                ('timestamp', models.DateField()),
                ('cost', models.FloatField()),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsInDish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.dish')),
                ('ingredientsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='DishesOfOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.dish')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.orders')),
            ],
        ),
    ]
