# Generated by Django 4.2.6 on 2023-10-21 10:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('allergens', models.CharField(default='/', max_length=500)),
                ('description', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.FloatField()),
                ('cost', models.FloatField()),
                ('minThreshold', models.IntegerField()),
                ('scadenza', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tableNumber', models.IntegerField()),
                ('timestamp', models.DateField(default=django.utils.timezone.now)),
                ('cost', models.FloatField(default=0.0)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('tableNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=500)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsInDish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantityNeeded', models.FloatField(default=0.0)),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.dish')),
                ('ingredientsId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.ingredients')),
            ],
        ),
        migrations.CreateModel(
            name='DishesOfOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('dishId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.dish')),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementApp.orders')),
            ],
        ),
    ]
