# Generated by Django 4.2.4 on 2023-08-09 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientsindish',
            name='quantityNeeded',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
