# Generated by Django 4.2.4 on 2023-09-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0002_ingredientsindish_quantityneeded_alter_orders_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='descripion',
            new_name='description',
        ),
    ]
