# Generated by Django 4.2.4 on 2023-09-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0003_rename_descripion_ingredients_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredients',
            old_name='minTheshold',
            new_name='minThreshold',
        ),
    ]
