# Generated by Django 4.2.4 on 2023-09-05 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0004_rename_mintheshold_ingredients_minthreshold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishesoforder',
            old_name='orderId',
            new_name='tableNumber',
        ),
    ]
