# Generated by Django 4.2.4 on 2023-09-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0005_rename_orderid_dishesoforder_tablenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishesoforder',
            old_name='tableNumber',
            new_name='orderId',
        ),
    ]
