# Generated by Django 4.2.4 on 2023-09-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0006_rename_tablenumber_dishesoforder_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='isAllergen',
        ),
        migrations.AddField(
            model_name='dish',
            name='allergens',
            field=models.CharField(default='/', max_length=500),
        ),
    ]
