# Generated by Django 4.2.4 on 2023-09-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0007_remove_ingredients_isallergen_dish_allergens'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishesoforder',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
