# Generated by Django 4.2.4 on 2023-10-02 17:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0008_dishesoforder_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='scadenza',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notification',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
